@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTYwNjQ1LCJpYXQiOjE3NDQ5NTcwNDUsImp0aSI6IjBjNGMxNjA5ZmM1ZTQzMDNiMGM2ZGRiY2E1NWVhM2ZlIiwidXNlcl9pZCI6MzV9.ue_oojN2SpeLeh7MShBcBUEQ6CI8D3HzwA0Bx9dBaUI
### get access token
POST http://localhost:8000/api/token
Content-Type: application/json

{
    "username": "admin",
    "password": "adminpassword"
}

### get user-related leave requests
GET http://localhost:8000/api/leaves
Authorization: Bearer {{access_token}}


### show all leave categories
GET http://localhost:8000/api/leaves/categories
Authorization: Bearer {{access_token}}

### create a new leave request
POST http://localhost:8000/api/leaves
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "effective_start_datetime": "2025-04-18T12:00:00+08:00",
    "effective_end_datetime": "2025-04-18T18:00:00+08:00",
    "category": 20
}

### create another new leave request
POST http://localhost:8000/api/leaves/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "effective_start_datetime": "2025-04-21T09:00:00+08:00",
    "effective_end_datetime": "2025-04-25T18:00:00+08:00",
    "category": 20
}

### approve a leave request
PUT http://localhost:8000/api/manage/leaves/56cbba5d-d7c5-4f54-be04-a7fcc091b298/approve/
Authorization: Bearer {{access_token}}

### reject a leave request
PUT http://localhost:8000/api/manage/leaves/56cbba5d-d7c5-4f54-be04-a7fcc091b298/reject/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "comment": "I don't like this leave request"
}