@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NTU1MTgwLCJpYXQiOjE3NDc1NTE1ODAsImp0aSI6IjMyZWNkOTViNTllNTQ1MTJiNzg3YmUwMzMyMWJhNGUwIiwidXNlcl9pZCI6MzB9.Sx9HUIv67fyRVSphXDCBn5nOJO1LdYKcupCc5kxYQ1w
@supervisor_access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NTU1MTYyLCJpYXQiOjE3NDc1NTE1NjIsImp0aSI6IjdjOWFiMGY1ZGRhNDQwOGU4MDk1MDMxMzBiMTRiZjk3IiwidXNlcl9pZCI6MzR9.jekU6gBJA43qf5lFKX5IesXKMT_VTPq7BuaUuK15458
@admin_access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NTU0MjM1LCJpYXQiOjE3NDc1NTA2MzUsImp0aSI6IjZjYWZjMmEwOTNmYjQwYTE4ZjQxMzY1ZmIzMDEwMTBiIiwidXNlcl9pZCI6MzV9.OeKpvEq1ySwt_Rpi7Z6Ua3FFbre-I2EHoYNSZ5OEeMU
@request_uuid = 56cbba5d-d7c5-4f54-be04-a7fcc091b298
### get access token
POST http://localhost:8000/api/token
Content-Type: application/json

{
    "username": "admin",
    "password": "adminpassword"
}


### get supervisor access token
POST http://localhost:8000/api/token
Content-Type: application/json

{
    "username": "atque390",
    "password": "password"
}


### get get normal user access token
POST http://localhost:8000/api/token
Content-Type: application/json

{
    "username": "aut106",
    "password": "password"
}


### get user-related leave requests
GET http://localhost:8000/api/leaves
Authorization: Bearer {{ access_token }}


### show all leave categories
GET http://localhost:8000/api/leaves/categories
Authorization: Bearer {{ access_token }}

### create a new leave request
POST http://localhost:8000/api/leaves
Authorization: Bearer {{ access_token }}
Content-Type: application/json

{
    "effective_start_datetime": "2025-05-26T12:00:00+08:00",
    "effective_end_datetime": "2025-05-26T18:00:00+08:00",
    "category": 16
}

### create another new leave request
POST http://localhost:8000/api/leaves/
Authorization: Bearer {{ access_token }}
Content-Type: application/json

{
    "effective_start_datetime": "2025-04-21T09:00:00+08:00",
    "effective_end_datetime": "2025-04-25T18:00:00+08:00",
    "category": 20
}

### get all pending (SUBMITTED) leave requests
GET http://localhost:8000/api/manage/leaves
Authorization: Bearer {{ admin_access_token }}

### approve a leave request
PUT http://localhost:8000/api/manage/leaves/{{ request_uuid }}/approve/
Authorization: Bearer {{ admin_access_token }}

### reject a leave request
PUT http://localhost:8000/api/manage/leaves/{{ request_uuid }}/reject/
Authorization: Bearer {{ admin_access_token }}
Content-Type: application/json

{
    "comment": "I don't like this leave request"
}