# Generated by Django 5.2 on 2025-04-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "男"), ("F", "女")],
                max_length=10,
                null=True,
                verbose_name="性別",
            ),
        ),
    ]
