# Generated by Django 5.2 on 2025-04-18 01:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="假別名稱")),
                (
                    "reset_policy",
                    models.CharField(
                        choices=[(0, "不會重置"), (1, "每月重置"), (2, "每年重置")],
                        default=0,
                        max_length=10,
                        verbose_name="重置規則",
                    ),
                ),
                (
                    "effective_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="生效日期（起）"
                    ),
                ),
                (
                    "effective_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="生效日期（止）"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="請假單號",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="送出時間"),
                ),
                (
                    "effective_start_datetime",
                    models.DateTimeField(verbose_name="生效起始時間"),
                ),
                (
                    "effective_end_datetime",
                    models.DateTimeField(verbose_name="生效結束時間"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "已送出"),
                            (1, "已鎖定"),
                            (2, "已同意"),
                            (3, "已拒絕"),
                        ],
                        default=0,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="附言"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="審核時間"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.leavecategory",
                        verbose_name="假別",
                    ),
                ),
                (
                    "process_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_leaves",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="審核主管",
                    ),
                ),
                (
                    "request_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申請人",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaveRequestPerDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="請假日期")),
                ("start_time", models.TimeField(verbose_name="開始時間")),
                ("end_time", models.TimeField(verbose_name="結束時間")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="per_day_entries",
                        to="api.leaverequest",
                        verbose_name="請假單",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleLeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_amount", models.IntegerField(verbose_name="預設可請時數")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.leavecategory",
                        verbose_name="假別",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.role",
                        verbose_name="職級",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remaining_amount", models.IntegerField(verbose_name="剩餘時數")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.leavecategory",
                        verbose_name="假別",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
        ),
    ]
