# Generated by Django 5.2 on 2025-04-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_leavecategory_reset_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavecategory",
            name="reset_policy",
            field=models.SmallIntegerField(
                choices=[(0, "不會重置"), (1, "每月重置"), (2, "每年重置")],
                default=0,
                verbose_name="重置規則",
            ),
        ),
    ]
