# Generated by Django 5.2 on 2025-04-18 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_leavecategory_reset_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="process_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_leaves",
                to=settings.AUTH_USER_MODEL,
                verbose_name="審核主管",
            ),
        ),
    ]
