# Generated by Django 5.2 on 2025-04-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_leaverequest_process_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="reason",
            field=models.TextField(blank=True, null=True, verbose_name="請假原因"),
        ),
    ]
