# Generated by Django 5.2 on 2025-05-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_leaverequest_reason"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ("effective_start_datetime",)},
        ),
    ]
